linter:
  rules:
    - missing_required_param
    - missing_return
    - cancel_subscriptions
    - close_sinks
    - prefer_is_not_empty
    - control_flow_in_finally
    - empty_statements
    - no_duplicate_case_values
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    - type_annotate_public_apis
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_positional_boolean_parameters
    - avoid_return_types_on_setters
    - avoid_unnecessary_containers
    - await_only_futures
    - curly_braces_in_flow_control_structures
    - library_names
    - prefer_contains
    - package_names
    - avoid_returning_null_for_future

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  errors:
    missing_required_param: error
    missing_return: error
    cancel_subscriptions: error
    close_sinks: warning
    control_flow_in_finally: error
    prefer_is_not_empty: error
    empty_statements: error
    no_duplicate_case_values: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    valid_regexps: error
    type_annotate_public_apis: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_positional_boolean_parameters: warning
    avoid_return_types_on_setters: error
    avoid_unnecessary_containers: error
    await_only_futures: error
    curly_braces_in_flow_control_structures: error
    library_names: error
    prefer_contains: error
    package_names: error
    avoid_returning_null_for_future: error
